### ISSUE TITLE
understanding qxt.local

### ISSUE THREAD

**Issue by omarcostahamido** [damonholzborn/QuaxTrip#1]
what is qxt.local?
and where are the qxt.local_L and qxt.local_R sends?

**Comment by damonholzborn** [comment]
Hi Omar,

qxt.local is for if you want to send audio from your own patch rather than from the audio ins. So qxt.local_L and qxt.local_R would be something you put in your own patch. There are a few little bonus features like this scattered about the patch, when I get the documentation done I’ll explain them all. Unfortunately, due to a minor household crisis, this week has been thrown into chaos so I probably won’t get to it as soon as I hoped. 

Thanks for checking out the patch.

Damon

**Comment by damonholzborn** [comment]
The various sends and receives are now documented in the manual and by example in lib/Quaxtrip Routing.maxpat

**Comment by omarcostahamido** [comment]
nice. thx Damon.
