### ISSUE TITLE
Local & Public IP address don't update 

### ISSUE THREAD

**Issue by fbotello** [damonholzborn/QuaxTrip#6]
I've noticed that when I open the conniption server window by clicking on the "Conniption Server" message I get the same list of IP addresses no matter what network I am connected to. I tested this out with other people and they seem to have the same issue. Might this be an issue with the js file that is used?

**Comment by damonholzborn** [comment]
As it turns out, this issue is about to be mooted when I release the new update (coming sometime in February). I added that list as a convenience, the idea being just to save a trip to network preferences, but in practice (even when it works properly) it's sometimes confusing since you might have multiple address (e.g. you're using ethernet, but wifi is still on). So I'm just axing the feature and will ad some instructions on how to find the address instead.

**Comment by fbotello** [comment]
This sounds good to me. It isn't too difficult of a process to find your IP via preferences or terminal. Also a great learning experience for anyone who might not know how.

**Comment by damonholzborn** [comment]
I haven't run into problems with this lately so I decided to keep the feature in after all. It'll still list multiple addresses (ethernet, wifi, for example) but that's just the info I get. If anyone still finds problems with this feature, please open a new issue.
